name = "Bigger Industrialisation"
author = "Lura Skye <l@veriny.tf>"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa6dc77555e5da8e9103cd0dc0fc2eba98d43d32f712266e1b8eac947bb73789"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
