name = "Bigger Industrialisation"
author = "Lura Skye <l@veriny.tf>"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fe98f25a171612726714652cf6b6c185bd96414b2ea5de82aa657e661a6c7af"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
