name = "Bigger Industrialisation"
author = "Lura Skye <l@veriny.tf>"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9df249e321b714f8e6b7725ee028cfc4ab708ecd250d0749456d4fd33a41cd91"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
