name = "Bigger Industrialisation"
author = "Lura Skye <l@veriny.tf>"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a46ec6421d4e9eacf06d7731326b75d9765a961ad082fa38b25856b372ee854e"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
