name = "Bigger Industrialisation"
author = "Lura Skye <l@veriny.tf>"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "461ce77129e5de1d73c9966e6dd43a5cbf81f5e37dcac04e9583eb550e2a8efb"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
