name = "Bigger Industrialisation"
author = "Lura Skye <l@veriny.tf>"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8febbc98b130495e5f6c8e4a0ae305c6f0fce46c8fc84c2dd5c3875037aa7b2c"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
