name = "Bigger Industrialisation"
author = "Lura Skye <l@veriny.tf>"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d00a7636937848cc83d56b3be2069c6fd336cbb27e0da3b1b594770c7bd8429"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
